name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências do backend
        working-directory: backend
        run: npm ci

      - name: Instalar dependências do frontend
        working-directory: frontend
        run: npm ci

      - name: Buildar o frontend
        working-directory: frontend
        run: npm run build

      - name: Rodar testes do backend
        working-directory: backend
        run: npm test
